### ISSUE TITLE
How can to be open the project on Qt Linguist?

### ISSUE THREAD

**Issue by Villelmo** [Arieleg/AreYouOk#1]
The translation file _**'/path/AreYouOk-main/AreYouOK_en_US.ts**_ "will not be loaded because it is empty.

**Comment by Arieleg** [comment]
Hello, I did not implement language support. Maybe in the future I will, or if you want to do it I will be happy to merge it.

**Comment by Villelmo** [comment]
I don't understand this **terminology**, maybe could investigate. 

I want to compile the project. I see that exist a file named _**AreYouOK.pro**_.

**Comment by Arieleg** [comment]
Check this for the Qt Linguist https://doc.qt.io/qt-6/qtlinguist-index.html, maybe it will help you.
As for the compilation of the project, I used Qt 6.0.2 for MinGW 8.1.0 64bit. I think you need to delete the .user file, open the .pro file with Qt Creator and do your own configuration.
The Qt documentation is really good, it might help you. https://doc.qt.io/all-topics.html
